/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-17 23:19:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editarProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/51944/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("jar:file:/C:/Users/51944/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1725567926718L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Editar Producto</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #f5f5f5;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("      margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .is-valid {\r\n");
      out.write("      border-color: green;\r\n");
      out.write("    }\r\n");
      out.write("    .is-invalid {\r\n");
      out.write("      border-color: red;\r\n");
      out.write("    }\r\n");
      out.write("    .error-message {\r\n");
      out.write("      color: red;\r\n");
      out.write("      font-size: 0.9em;\r\n");
      out.write("      margin-top: 5px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2 class=\"mb-4\">Editar Producto</h2>\r\n");
      out.write("  <form class=\"row g-3 needs-validation\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editarProduct\" method=\"post\" id=\"productForm\" novalidate>\r\n");
      out.write("    <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> <!-- Asegúrate de que estás pasando el ID -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"errorAlert\" class=\"alert alert-danger d-none\">\r\n");
      out.write("      Error al enviar el formulario. Por favor, revise los campos.\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"name\" class=\"form-label\">Nombre</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\">\r\n");
      out.write("        El nombre no debe contener números.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"description\" class=\"form-label\">Descripción</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"description\" name=\"description\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\">\r\n");
      out.write("        Proporciona una descripción para el producto.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("      <label for=\"category\" class=\"form-label\">Categoría</label>\r\n");
      out.write("      <select class=\"form-select\" id=\"category\" name=\"category\" required>\r\n");
      out.write("        <option value=\"\">Seleccione una categoría...</option>\r\n");
      out.write("        <option value=\"Embutidos\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Embutidos'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Embutidos</option>\r\n");
      out.write("        <option value=\"Bebidas\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Bebidas'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Bebidas</option>\r\n");
      out.write("        <option value=\"Lácteos\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Lácteos'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Lácteos</option>\r\n");
      out.write("        <option value=\"Snacks\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Snacks'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Snacks</option>\r\n");
      out.write("        <option value=\"Conservas\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Conservas'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Conservas</option>\r\n");
      out.write("        <option value=\"Condimentos\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Condimentos'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Condimentos</option>\r\n");
      out.write("        <option value=\"Higiene\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Higiene'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Higiene</option>\r\n");
      out.write("        <option value=\"Abarrotes\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Abarrotes'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Abarrotes</option>\r\n");
      out.write("        <option value=\"Frutas y Verduras\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Frutas y Verduras'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Frutas y Verduras</option>\r\n");
      out.write("        <option value=\"Carnes\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Carnes'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Carnes</option>\r\n");
      out.write("        <option value=\"Granos\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Granos'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Granos</option>\r\n");
      out.write("        <option value=\"Panadería\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Panadería'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Panadería</option>\r\n");
      out.write("        <option value=\"Confitería\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Confitería'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Confitería</option>\r\n");
      out.write("        <option value=\"Cuidado Personal\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Cuidado Personal'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Cuidado Personal</option>\r\n");
      out.write("        <option value=\"Limpieza\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Limpieza'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Limpieza</option>\r\n");
      out.write("        <option value=\"Mascotas\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Mascotas'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Mascotas</option>\r\n");
      out.write("        <option value=\"Congelados\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Congelados'.equals(producto.category) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Congelados</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\" id=\"categoryError\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.categoryError != null ? requestScope.categoryError : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("        Seleccione una categoría.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("      <label for=\"trade_mark\" class=\"form-label\">Marca</label>\r\n");
      out.write("      <select class=\"form-select\" id=\"trade_mark\" name=\"trade_mark\" required>\r\n");
      out.write("        <option value=\"\">Seleccione una marca...</option>\r\n");
      out.write("        <option value=\"Gloria\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Gloria'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Gloria</option>\r\n");
      out.write("        <option value=\"Alicorp\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Alicorp'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Alicorp</option>\r\n");
      out.write("        <option value=\"San Fernando\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'San Fernando'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">San Fernando</option>\r\n");
      out.write("        <option value=\"Inka Kola\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Inka Kola'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Inka Kola</option>\r\n");
      out.write("        <option value=\"Backus\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Backus'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Backus</option>\r\n");
      out.write("        <option value=\"D'Onofrio\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'D\\'Onofrio'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">D'Onofrio</option>\r\n");
      out.write("        <option value=\"Ajinomoto\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Ajinomoto'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Ajinomoto</option>\r\n");
      out.write("        <option value=\"Laive\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Laive'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Laive</option>\r\n");
      out.write("        <option value=\"Perú Cola\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Perú Cola'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Perú Cola</option>\r\n");
      out.write("        <option value=\"Cusqueña\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Cusqueña'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Cusqueña</option>\r\n");
      out.write("        <option value=\"Milkito\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Milkito'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Milkito</option>\r\n");
      out.write("        <option value=\"Danlac\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Danlac'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Danlac</option>\r\n");
      out.write("        <option value=\"Bonlé\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Bonlé'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Bonlé</option>\r\n");
      out.write("        <option value=\"Winter's\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Winter\\'s'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Winter's</option>\r\n");
      out.write("        <option value=\"Field\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Field'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Field</option>\r\n");
      out.write("        <option value=\"Nicolini\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Nicolini'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Nicolini</option>\r\n");
      out.write("        <option value=\"Florida\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Florida'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Florida</option>\r\n");
      out.write("        <option value=\"Compass\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Compass'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Compass</option>\r\n");
      out.write("        <option value=\"Fanny\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Fanny'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Fanny</option>\r\n");
      out.write("        <option value=\"Sapolio\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Sapolio'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Sapolio</option>\r\n");
      out.write("        <option value=\"Intradevco\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Intradevco'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Intradevco</option>\r\n");
      out.write("        <option value=\"San Mateo\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'San Mateo'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">San Mateo</option>\r\n");
      out.write("        <option value=\"Ajíno-men\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Ajíno-men'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Ajíno-men</option>\r\n");
      out.write("        <option value=\"Kola Real\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Kola Real'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Kola Real</option>\r\n");
      out.write("        <option value=\"Negrita\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Negrita'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Negrita</option>\r\n");
      out.write("        <option value=\"Molitalia\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Molitalia'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Molitalia</option>\r\n");
      out.write("        <option value=\"Royal\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Royal'.equals(producto.tradeMark) ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Royal</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\" id=\"tradeMarkError\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.tradeMarkError != null ? requestScope.tradeMarkError : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("        Seleccione una Marca.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"stock\" class=\"form-label\">Cantidad</label>\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" id=\"stock\" name=\"stock\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.stock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" min=\"0\" required>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\">\r\n");
      out.write("        Ingrese una cantidad válida.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-4\">\r\n");
      out.write("      <label for=\"price\" class=\"form-label\">Precio</label>\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" id=\"price\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" min=\"0\" step=\"0.01\" required>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\">\r\n");
      out.write("        Ingrese un precio válido.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <label for=\"expiry_date\" class=\"form-label\">Fecha de Vencimiento</label>\r\n");
      out.write("      <input type=\"date\" class=\"form-control\" id=\"expiry_date\" name=\"expiry_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formattedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("      <div class=\"invalid-feedback\">La fecha debe ser después de 10 meses.</div>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-md-5\">\r\n");
      out.write("      <label for=\"code_product\" class=\"form-label\">Código del Producto</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"code_product\" name=\"code_product\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.codeProduct}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Ingrese el codigo del producto...\" required pattern=\"[A-Za-z0-9]{4}\">\r\n");
      out.write("      <div class=\"invalid-feedback\">Proporciona un código válido.</div>\r\n");
      out.write("      <div class=\"valid-feedback\">\r\n");
      out.write("        ¡Se ve bien!\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"invalid-feedback\">\r\n");
      out.write("        Ingrese un codigo válido.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-12\">\r\n");
      out.write("      <button class=\"btn btn-primary\" type=\"submit\">Actualizar Producto</button>\r\n");
      out.write("      <a href=\"listarProductos\" class=\"btn btn-secondary\">Cancelar</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("    const form = document.getElementById(\"productForm\");\r\n");
      out.write("    const inputs = form.querySelectorAll(\"input, select\");\r\n");
      out.write("    const errorAlert = document.getElementById(\"errorAlert\");\r\n");
      out.write("\r\n");
      out.write("    // Función para aplicar la clase is-valid a los campos con valores válidos\r\n");
      out.write("    function aplicarValidacionesIniciales() {\r\n");
      out.write("      inputs.forEach(input => {\r\n");
      out.write("        if (input.value.trim() && validarCampo(input)) {\r\n");
      out.write("          // Si el valor está presente y el campo es válido, asigna la clase is-valid\r\n");
      out.write("          input.classList.remove(\"is-invalid\");\r\n");
      out.write("          input.classList.add(\"is-valid\");\r\n");
      out.write("        } else {\r\n");
      out.write("          // Si no es válido, asigna la clase is-invalid (por si los valores previos no eran válidos)\r\n");
      out.write("          input.classList.remove(\"is-valid\");\r\n");
      out.write("          input.classList.add(\"is-invalid\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Añadir eventos de validación en tiempo real\r\n");
      out.write("    inputs.forEach(input => {\r\n");
      out.write("      input.addEventListener(\"input\", () => validarCampo(input));\r\n");
      out.write("      input.addEventListener(\"change\", () => validarCampo(input));\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Aplicar las validaciones iniciales cuando la página se carga\r\n");
      out.write("    aplicarValidacionesIniciales();\r\n");
      out.write("\r\n");
      out.write("    // Manejar el evento submit\r\n");
      out.write("    form.addEventListener(\"submit\", (event) => {\r\n");
      out.write("      event.preventDefault(); // Prevenir el envío normal del formulario\r\n");
      out.write("      let esValido = true;\r\n");
      out.write("\r\n");
      out.write("      // Limpiar el mensaje de error\r\n");
      out.write("      errorAlert.classList.add(\"d-none\");\r\n");
      out.write("\r\n");
      out.write("      // Validar cada campo\r\n");
      out.write("      inputs.forEach(input => {\r\n");
      out.write("        if (!validarCampo(input)) {\r\n");
      out.write("          esValido = false; // Si algún campo no es válido\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Si todos los campos son válidos, enviar el formulario\r\n");
      out.write("      if (esValido) {\r\n");
      out.write("        form.submit(); // Elimina esta línea si solo quieres manejar el envío con AJAX\r\n");
      out.write("      } else {\r\n");
      out.write("        errorAlert.classList.remove(\"d-none\");\r\n");
      out.write("        errorAlert.textContent = \"Por favor, corrige los errores antes de enviar.\";\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Función para validar cada campo\r\n");
      out.write("    function validarCampo(input) {\r\n");
      out.write("      let esValido = true;\r\n");
      out.write("\r\n");
      out.write("      // Validaciones básicas\r\n");
      out.write("      if (input.hasAttribute(\"required\") && !input.value.trim()) {\r\n");
      out.write("        esValido = false;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Validaciones específicas\r\n");
      out.write("      switch (input.id) {\r\n");
      out.write("        case \"name\":\r\n");
      out.write("          if (/\\d/.test(input.value)) {\r\n");
      out.write("            esValido = false; // No permitir números en el nombre\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"description\":\r\n");
      out.write("          if (input.value.trim() === '') {\r\n");
      out.write("            esValido = false; // La descripción no debe estar vacía\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"category\":\r\n");
      out.write("          if (input.value === '' || input.value === null) {\r\n");
      out.write("            esValido = false; // La categoría debe estar seleccionada\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"expiry_date\":\r\n");
      out.write("          const fechaVencimiento = new Date(input.value);\r\n");
      out.write("          const fechaLimite = new Date();\r\n");
      out.write("          fechaLimite.setMonth(fechaLimite.getMonth() + 10);\r\n");
      out.write("          if (fechaVencimiento < fechaLimite) {\r\n");
      out.write("            esValido = false; // La fecha debe ser al menos 10 meses en el futuro\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"stock\":\r\n");
      out.write("          if (input.value <= 0) {\r\n");
      out.write("            esValido = false; // La cantidad debe ser mayor que 0\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"price\":\r\n");
      out.write("          if (parseFloat(input.value) <= 0) {\r\n");
      out.write("            esValido = false; // El precio debe ser mayor que cero\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("        case \"code_product\":\r\n");
      out.write("          if (!/^[A-Za-z0-9]{4}$/.test(input.value)) {\r\n");
      out.write("            esValido = false; // Código debe tener exactamente 4 caracteres alfanuméricos\r\n");
      out.write("          }\r\n");
      out.write("          break;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      // Aplicar clases de Bootstrap\r\n");
      out.write("      if (esValido) {\r\n");
      out.write("        input.classList.remove(\"is-invalid\");\r\n");
      out.write("        input.classList.add(\"is-valid\");\r\n");
      out.write("      } else {\r\n");
      out.write("        input.classList.remove(\"is-valid\");\r\n");
      out.write("        input.classList.add(\"is-invalid\");\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      return esValido;\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
